/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.uiprefab {
    export class BronzewareContentUIUI extends Laya.View {
		public UI_bg_Panel:Laya.Panel;
		public UI_content_Img:Laya.Image;
		public UI_textContent_Panel:Laya.Panel;
		public UI_content_Label:Laya.Label;
		public UI_text_Img:Laya.Image;
		public UI_next_Btn:Laya.Button;
		public UI_progressContent_Panel:Laya.Panel;
		public UI_progressBg_Panel:Laya.Panel;
		public UI_progressColor_Panel:Laya.Panel;
		public UI_progress0:Laya.Panel;
		public UI_progress0_color:Laya.Panel;
		public UI_progress1:Laya.Panel;
		public UI_progress1_color:Laya.Panel;
		public UI_progress2:Laya.Panel;
		public UI_progress2_color:Laya.Panel;
		public UI_progress3:Laya.Panel;
		public UI_progress3_color:Laya.Panel;
		public UI_progress4:Laya.Panel;
		public UI_progress4_color:Laya.Panel;
		public UI_progress5:Laya.Panel;
		public UI_progress5_color:Laya.Panel;
		public UI_progress6:Laya.Panel;
		public UI_progress6_color:Laya.Panel;
		public UI_progress7:Laya.Panel;
		public UI_progress7_color:Laya.Panel;
		public UI_progress8:Laya.Panel;
		public UI_progress8_color:Laya.Panel;
		public UI_progress9:Laya.Panel;
		public UI_progress9_color:Laya.Panel;
		public UI_Title:Laya.Image;
		public UI_start_Img:Laya.Image;
		public UI_start_Btn:Laya.Button;
		public UI_3DModelOpPrompt:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("uiprefab/BronzewareContentUI");
        }
    }
    REG("ui.uiprefab.BronzewareContentUIUI",BronzewareContentUIUI);
    export class CalibrationUIUI extends Laya.View {
		public UI_Calibration:Laya.Image;
		public UI_DialPlate:Laya.Image;
		public UI_PauseZone1:Laya.Image;
		public UI_PauseZone2:Laya.Image;
		public UI_PauseZone3:Laya.Image;
		public UI_PauseZone4:Laya.Image;
		public UI_pointer:Laya.Image;
		public UI_prompt:Laya.Image;
		public UI_mistake:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("uiprefab/CalibrationUI");
        }
    }
    REG("ui.uiprefab.CalibrationUIUI",CalibrationUIUI);
    export class ColorMatchingUIUI extends Laya.View {
		public UI_content_Image:Laya.Image;
		public UI_yellow_Btn:Laya.Button;
		public UI_black_Btn:Laya.Button;
		public UI_green_Btn:Laya.Button;
		public UI_Block1:Laya.Image;
		public UI_Block2:Laya.Image;
		public UI_Block3:Laya.Image;
		public UI_wrong_Img:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("uiprefab/ColorMatchingUI");
        }
    }
    REG("ui.uiprefab.ColorMatchingUIUI",ColorMatchingUIUI);
    export class EndUIUI extends Laya.View {
		public UI_End2Btn:Laya.Button;
		public UI_End1Btn:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("uiprefab/EndUI");
        }
    }
    REG("ui.uiprefab.EndUIUI",EndUIUI);
    export class LoadingUIUI extends Laya.View {
		public UI_LoadingIcon:Laya.Image;
		public UI_ProgressBottom:Laya.Image;
		public UI_ProgressUpper:Laya.Image;
		public UI_ProgressMask:Laya.Image;
		public UI_Prompt_Text:Laya.Label;
        public static  uiView:any ={"type":"View","props":{"y":0,"x":0,"width":1920,"top":0,"right":0,"left":0,"height":1080,"bottom":0},"compId":2,"child":[{"type":"Image","props":{"top":0,"skin":"uiatlas/loading/gamebg.jpg","right":0,"name":"Bg","left":0,"bottom":0},"compId":6},{"type":"Image","props":{"var":"UI_LoadingIcon","skin":"uiatlas/loading/title.png","centerY":0,"centerX":0},"compId":13,"child":[{"type":"Image","props":{"y":-215,"x":-192},"compId":14}]},{"type":"Image","props":{"width":400,"var":"UI_ProgressBottom","skin":"uiatlas/loading/img_progress_0.png","name":"UI_ProgressBottom","height":76,"centerY":343,"centerX":0,"anchorY":0,"anchorX":0,"alpha":1,"sizeGrid":"0,50,0,50"},"compId":7,"child":[{"type":"Image","props":{"y":0,"x":0,"width":400,"var":"UI_ProgressUpper","skin":"uiatlas/loading/img_progress_1.png","name":"UI_ProgressUpper","height":76,"sizeGrid":"0,50,0,50"},"compId":8,"child":[{"type":"Image","props":{"y":0,"x":0,"width":400,"var":"UI_ProgressMask","skin":"uiatlas/loading/img_progress_1.png","renderType":"mask","name":"UI_ProgressMask","height":76,"sizeGrid":"0,50,0,50"},"compId":9}]},{"type":"Label","props":{"var":"UI_Prompt_Text","valign":"top","top":76,"fontSize":30,"font":"SimHei","color":"#0160dd","centerX":0,"align":"center"},"compId":21}]}],"loadList":["uiatlas/loading/gamebg.jpg","uiatlas/loading/title.png","uiatlas/loading/img_progress_0.png","uiatlas/loading/img_progress_1.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadingUIUI.uiView);
        }
    }
    REG("ui.uiprefab.LoadingUIUI",LoadingUIUI);
    export class StartUIUI extends Laya.View {
		public UI_Start2Btn:Laya.Button;
		public UI_Start1Btn:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("uiprefab/StartUI");
        }
    }
    REG("ui.uiprefab.StartUIUI",StartUIUI);
}